In [1]:
import pandas as pd

In [2]:
auctions = pd.read_csv("auctions.csv")

In [38]:
installs = pd.read_csv("installs.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (4,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
auctions = auctions[["date", "device_id"]]

In [5]:
auctions["is_install"] = False

In [6]:
installs.head()

,created,application_id,ref_type,ref_hash,click_hash,attributed,implicit,device_countrycode,device_brand,device_model,session_user_agent,user_agent,event_uuid,kind,wifi,trans_id,ip_address,device_language
0,2019-04-24 06:23:29.495,1,1494519392962156891,4716708407362582887,NaN,False,True,6287817205707153877,NaN,3.739127e+17,adjust.com,NaN,79837499-2f2a-4605-a663-e322f759424f,app_open,NaN,NaN,4243443387795468703,3.301378e+18
1,2019-04-24 02:06:01.032,1,1494519392962156891,7143568733100935872,NaN,False,False,6287817205707153877,NaN,7.805539e+18,adjust.com,NaN,NaN,NaN,NaN,NaN,4724288679627032761,3.301378e+18
2,2019-04-20 10:15:36.274,1,1494519392962156891,5230323462636548010,NaN,False,True,6287817205707153877,NaN,8.355496e+18,adjust.com,NaN,dda99e3c-9c4b-487d-891c-79f0a02cb4a8,app_open,NaN,NaN,8291809486355890410,4.060930e+18
3,2019-04-20 21:56:47.151,1,1494519392962156891,5097163995161606833,NaN,False,True,6287817205707153877,NaN,2.355772e+18,adjust.com,NaN,7010c3ce-0fcf-46c6-9be8-374cc0e20af4,app_open,NaN,NaN,4006811922873399949,3.301378e+18
4,2019-04-20 22:40:41.239,1,1494519392962156891,6328027616411983332,NaN,False,False,6287817205707153877,NaN,6.156971e+18,adjust.com,NaN,NaN,NaN,NaN,NaN,3386455054590810771,3.301378e+18

In [7]:
installs = installs[["created", "ref_hash"]]

In [8]:
installs["is_install"] = True

In [9]:
installs = installs.rename(index=str,columns={"created": "date", "ref_hash": "device_id"})

In [10]:
installs.head()

                      date            device_id  is_install
0  2019-04-24 06:23:29.495  4716708407362582887        True
1  2019-04-24 02:06:01.032  7143568733100935872        True
2  2019-04-20 10:15:36.274  5230323462636548010        True
3  2019-04-20 21:56:47.151  5097163995161606833        True
4  2019-04-20 22:40:41.239  6328027616411983332        True

In [11]:
auctions.head()

                         date            device_id  is_install
0  2019-04-23 18:58:00.842116  2564673204772915246       False
1  2019-04-23 18:58:01.530771  4441121667607578179       False
2  2019-04-23 18:58:01.767562  7721769811471055264       False
3  2019-04-23 18:58:02.363468  6416039086842158968       False
4  2019-04-23 18:58:02.397559  1258642015983312729       False

In [12]:
concatenate_installs_auctions = pd.concat([installs, auctions])

In [13]:
ordered = concatenate_installs_auctions.sort_values(by=["device_id",'date'])

In [14]:
ordered.head()

                                date       device_id  is_install
46742        2019-04-21 19:17:47.657  40621409780134        True
36601349  2019-04-23 15:00:57.222979  40621409780134       False
398921       2019-04-18 21:11:50.326  41863526108385        True
249204       2019-04-18 21:11:51.966  41863526108385        True
112218       2019-04-18 21:17:11.946  41863526108385        True

### Feature cantidad de installs y auction por dispositivo

In [15]:
auctions["Cantidad_total_de_auction"] = 1

In [92]:
cantidad_total_auctions = auctions.groupby("device_id").agg({"Cantidad_total_de_auction":"sum"}).reset_index()
cantidad_total_auctions

                  device_id  Cantidad_total_de_auction
0            40621409780134                          1
1            41863526108385                         35
2            69039685746313                          4
3           135153013040192                          8
4           161514654074162                          6
5           168103949904656                          1
6           181891380775191                          1
7           186034136943920                         66
8           283297668933729                          1
9           295841792051458                          1
10          345999128501141                         74
11          360710529886978                         56
12          365882020742330                          7
13          407152743717620                          1
14          416301579449694                        111
15          456015810461357                          2
16          473668258229864                         49
17          475635010681369                          1
18          501790157110512                         77
19          519199987760489                          5
20          526030445561483                         23
21          530786270564316                         10
22          558877640599287                          1
23          607090818352855                          2
24          608739959707707                          2
25          622102439689666                         30
26          627959756577621                         15
27          643594200494946                          7
28          645011308561636                          6
29          651957297814003                          3
...                     ...                        ...
475308  9222802779964047967                         63
475309  9222809061253378785                        423
475310  9222820903899321555                         13
475311  9222825313616050213                         19
475312  9222828776091827087                         85
475313  9222830073132521659                         87
475314  9222833096174851045                          7
475315  9222846891248817195                          1
475316  9222848912066710170                         11
475317  9222856470568969120                          9
475318  9222891164638072546                          6
475319  9222941581432951568                         27
475320  9222948803125074466                        217
475321  9222949346293344736                         61
475322  9222957264925735246                          2
475323  9222980782941976521                         11
475324  9223059472116696420                         19
475325  9223135580643723279                          7
475326  9223145249047741674                        112
475327  9223163483138526566                         73
475328  9223186171940415898                        275
475329  9223189551280812934                         47
475330  9223229584859890420                         79
475331  9223231006535555583                         22
475332  9223238938580369700                         88
475333  9223252295312976945                         19
475334  9223285798152466987                         62
475335  9223343217005320170                          5
475336  9223356715682543611                        245
475337  9223365873867066370                        105

[475338 rows x 2 columns]

In [93]:
auctions.loc[((auctions["date"] < "2019-04-21")), "Periodo"] = "Primero"
auctions.loc[((auctions["date"] > "2019-04-20") & (auctions["date"] < "2019-04-24") ), "Periodo"] = "Segundo"
auctions.loc[((auctions["date"] > "2019-04-23")), "Periodo"] = "Tercero"

In [94]:
auctions_periodos = auctions.groupby(["device_id","Periodo"]).agg({"Cantidad_total_de_auction":"sum"})

In [95]:
auctions_periodos = auctions_periodos.unstack().reset_index()
auctions_periodos.fillna(0, inplace= True)

In [96]:
auctions_periodos.columns = ["device_id","1_Periodo_Auctions","2_Periodo_Auctions","3_Periodo_Auctions"]

In [97]:
auctions_periodos

,device_id,1_Periodo_Auctions,2_Periodo_Auctions,3_Periodo_Auctions
0,40621409780134,0.0,0.0,1.0
1,41863526108385,1.0,34.0,0.0
2,69039685746313,0.0,0.0,4.0
3,135153013040192,0.0,8.0,0.0
4,161514654074162,6.0,0.0,0.0
5,168103949904656,0.0,0.0,1.0
6,181891380775191,0.0,1.0,0.0
7,186034136943920,2.0,51.0,13.0
8,283297668933729,1.0,0.0,0.0
9,295841792051458,0.0,1.0,0.0
10,345999128501141,47.0,2.0,25.0
11,360710529886978,10.0,3.0,43.0
12,365882020742330,4.0,1.0,2.0
13,407152743717620,1.0,0.0,0.0
14,416301579449694,10.0,39.0,62.0
15,456015810461357,0.0,0.0,2.0
16,473668258229864,46.0,2.0,1.0
17,475635010681369,1.0,0.0,0.0
18,501790157110512,50.0,26.0,1.0
19,519199987760489,0.0,2.0,3.0
20,526030445561483,2.0,1.0,20.0
21,530786270564316,5.0,4.0,1.0
22,558877640599287,0.0,1.0,0.0
23,607090818352855,1.0,1.0,0.0
24,608739959707707,1.0,1.0,0.0
25,622102439689666,14.0,16.0,0.0
26,627959756577621,2.0,3.0,10.0
27,643594200494946,3.0,0.0,4.0
28,645011308561636,4.0,0.0,2.0
29,651957297814003,0.0,3.0,0.0
...,...,...,...,...
475308,9222802779964047967,7.0,56.0,0.0
475309,9222809061253378785,0.0,154.0,269.0
475310,9222820903899321555,5.0,2.0,6.0
475311,9222825313616050213,0.0,0.0,19.0
475312,9222828776091827087,1.0,0.0,84.0
475313,9222830073132521659,12.0,0.0,75.0
475314,9222833096174851045,2.0,5.0,0.0
475315,9222846891248817195,0.0,0.0,1.0
475316,9222848912066710170,5.0,1.0,5.0
475317,9222856470568969120,0.0,6.0,3.0
475318,9222891164638072546,0.0,6.0,0.0
475319,9222941581432951568,5.0,2.0,20.0
475320,9222948803125074466,1.0,9.0,207.0
475321,9222949346293344736,8.0,9.0,44.0
475322,9222957264925735246,0.0,2.0,0.0
475323,9222980782941976521,0.0,1.0,10.0
475324,9223059472116696420,5.0,2.0,12.0
475325,9223135580643723279,2.0,3.0,2.0
475326,9223145249047741674,32.0,23.0,57.0
475327,9223163483138526566,41.0,14.0,18.0
475328,9223186171940415898,3.0,4.0,268.0
475329,9223189551280812934,0.0,0.0,47.0
475330,9223229584859890420,31.0,0.0,48.0
475331,9223231006535555583,5.0,6.0,11.0
475332,9223238938580369700,0.0,14.0,74.0
475333,9223252295312976945,17.0,2.0,0.0
475334,9223285798152466987,2.0,16.0,44.0
475335,9223343217005320170,0.0,2.0,3.0
475336,9223356715682543611,147.0,4.0,94.0
475337,9223365873867066370,0.0,5.0,100.0

In [99]:
#Joineo 
auctions_cantidades = auctions_periodos.merge(cantidad_total_auctions, how = "inner", on = "device_id")

### Installs

In [ ]:
installs = pd.read_csv("installs.csv")

In [75]:
installs = installs.rename(index=str,columns={"created": "date", "ref_hash": "device_id"})

In [76]:
installs["Cantidad_total_de_install"] = 1

In [77]:
cantidad_total_installs = installs.groupby("device_id").agg({"Cantidad_total_de_install":"sum"}).reset_index()
cantidad_total_installs

                  device_id  Cantidad_total_de_install
0            40621409780134                          1
1            41863526108385                          4
2            90072729247980                          1
3           135153013040192                          1
4           161514654074162                          1
5           168103949904656                          1
6           186034136943920                          1
7           283297668933729                          1
8           342614246084071                          1
9           345999128501141                          1
10          347785260789835                          1
11          365882020742330                          1
12          416301579449694                          1
13          420449720220692                          1
14          448610188195811                          2
15          456015810461357                          1
16          457867161681660                          1
17          468235013311868                          1
18          475635010681369                          2
19          519199987760489                          1
20          530786270564316                          1
21          538200907470757                          1
22          558877640599287                          1
23          622102439689666                          3
24          642751118419841                          1
25          655267966876774                          1
26          717556230663455                          1
27          719819620272773                          1
28          732881181016646                          1
29          759186287310366                          1
...                     ...                        ...
393535  9222439452676054246                          1
393536  9222445878176178987                          1
393537  9222505600439168461                          1
393538  9222517399250029400                          1
393539  9222605308741024421                          2
393540  9222608508750105493                          1
393541  9222775201174486974                          1
393542  9222809061253378785                          1
393543  9222820903899321555                          2
393544  9222828776091827087                          3
393545  9222848912066710170                          1
393546  9222856470568969120                          1
393547  9222861184027496933                          1
393548  9222891164638072546                          1
393549  9222941581432951568                          1
393550  9222957264925735246                          4
393551  9223065111245755115                          1
393552  9223066346652706056                          1
393553  9223135580643723279                          1
393554  9223180934071401185                          1
393555  9223189551280812934                          2
393556  9223229584859890420                          1
393557  9223231006535555583                          1
393558  9223250784891904112                          1
393559  9223252295312976945                          2
393560  9223291601074715510                          1
393561  9223314893254762361                          1
393562  9223332684447638624                          1
393563  9223336706138545892                          1
393564  9223365873867066370                          1

[393565 rows x 2 columns]

In [78]:
installs.loc[((installs["date"] < "2019-04-21")), "Periodo"] = "Primero"
installs.loc[((installs["date"] > "2019-04-20") & (installs["date"] < "2019-04-24") ), "Periodo"] = "Segundo"
installs.loc[((installs["date"] > "2019-04-23")), "date"] = "Tercero"

In [79]:
installs_periodos = installs.groupby(["device_id","Periodo"]).agg({"Cantidad_total_de_install":"sum"})

In [80]:
periodos_installs = installs_periodos.unstack().reset_index()
periodos_installs.fillna(0, inplace= True)

In [81]:
periodos_installs.columns = ["device_id","1_Periodo_Installs","2_Periodo_Installs","3_Periodo_Installs"]

In [82]:
#Joineo 
installs_cantidades = periodos_installs.merge(cantidad_total_installs, how = "inner", on = "device_id")

In [83]:
installs_cantidades

,device_id,1_Periodo_Installs,2_Periodo_Installs,3_Periodo_Installs,Cantidad_total_de_install
0,40621409780134,0.0,1.0,0.0,1
1,41863526108385,4.0,0.0,0.0,4
2,90072729247980,0.0,0.0,1.0,1
3,135153013040192,0.0,1.0,0.0,1
4,161514654074162,0.0,1.0,0.0,1
5,168103949904656,0.0,1.0,0.0,1
6,186034136943920,1.0,0.0,0.0,1
7,283297668933729,0.0,1.0,0.0,1
8,342614246084071,0.0,0.0,1.0,1
9,345999128501141,0.0,1.0,0.0,1
10,347785260789835,0.0,0.0,1.0,1
11,365882020742330,1.0,0.0,0.0,1
12,416301579449694,0.0,0.0,1.0,1
13,420449720220692,0.0,0.0,1.0,1
14,448610188195811,0.0,0.0,2.0,2
15,456015810461357,0.0,0.0,1.0,1
16,457867161681660,0.0,1.0,0.0,1
17,468235013311868,0.0,1.0,0.0,1
18,475635010681369,0.0,2.0,0.0,2
19,519199987760489,1.0,0.0,0.0,1
20,530786270564316,1.0,0.0,0.0,1
21,538200907470757,0.0,1.0,0.0,1
22,558877640599287,1.0,0.0,0.0,1
23,622102439689666,0.0,2.0,1.0,3
24,642751118419841,0.0,1.0,0.0,1
25,655267966876774,1.0,0.0,0.0,1
26,717556230663455,0.0,0.0,1.0,1
27,719819620272773,0.0,0.0,1.0,1
28,732881181016646,0.0,1.0,0.0,1
29,759186287310366,0.0,0.0,1.0,1
...,...,...,...,...,...
393535,9222439452676054246,0.0,0.0,1.0,1
393536,9222445878176178987,0.0,1.0,0.0,1
393537,9222505600439168461,0.0,1.0,0.0,1
393538,9222517399250029400,1.0,0.0,0.0,1
393539,9222605308741024421,2.0,0.0,0.0,2
393540,9222608508750105493,0.0,0.0,1.0,1
393541,9222775201174486974,0.0,0.0,1.0,1
393542,9222809061253378785,0.0,0.0,1.0,1
393543,9222820903899321555,0.0,2.0,0.0,2
393544,9222828776091827087,0.0,0.0,3.0,3
393545,9222848912066710170,0.0,0.0,1.0,1
393546,9222856470568969120,0.0,1.0,0.0,1
393547,9222861184027496933,1.0,0.0,0.0,1
393548,9222891164638072546,0.0,1.0,0.0,1
393549,9222941581432951568,0.0,1.0,0.0,1
393550,9222957264925735246,4.0,0.0,0.0,4
393551,9223065111245755115,0.0,1.0,0.0,1
393552,9223066346652706056,1.0,0.0,0.0,1
393553,9223135580643723279,0.0,0.0,1.0,1
393554,9223180934071401185,0.0,1.0,0.0,1
393555,9223189551280812934,2.0,0.0,0.0,2
393556,9223229584859890420,0.0,0.0,1.0,1
393557,9223231006535555583,0.0,1.0,0.0,1
393558,9223250784891904112,0.0,1.0,0.0,1
393559,9223252295312976945,1.0,0.0,1.0,2
393560,9223291601074715510,0.0,0.0,1.0,1
393561,9223314893254762361,0.0,0.0,1.0,1
393562,9223332684447638624,0.0,1.0,0.0,1
393563,9223336706138545892,0.0,0.0,1.0,1
393564,9223365873867066370,0.0,0.0,1.0,1

### Mergeo installs con auctions

In [91]:
auctions_installs_cantidades = installs_cantidades.merge(auctions_cantidades, how = "inner", on = "device_id")

In [89]:
auctions_installs_cantidades

,device_id,1_Periodo_Installs_x,2_Periodo_Installs_x,3_Periodo_Installs_x,Cantidad_total_de_install_x,1_Periodo_Installs_y,2_Periodo_Installs_y,3_Periodo_Installs_y,Cantidad_total_de_install_y
0,40621409780134,0.0,1.0,0.0,1,0.0,1.0,0.0,1
1,41863526108385,4.0,0.0,0.0,4,4.0,0.0,0.0,4
2,90072729247980,0.0,0.0,1.0,1,0.0,0.0,1.0,1
3,135153013040192,0.0,1.0,0.0,1,0.0,1.0,0.0,1
4,161514654074162,0.0,1.0,0.0,1,0.0,1.0,0.0,1
5,168103949904656,0.0,1.0,0.0,1,0.0,1.0,0.0,1
6,186034136943920,1.0,0.0,0.0,1,1.0,0.0,0.0,1
7,283297668933729,0.0,1.0,0.0,1,0.0,1.0,0.0,1
8,342614246084071,0.0,0.0,1.0,1,0.0,0.0,1.0,1
9,345999128501141,0.0,1.0,0.0,1,0.0,1.0,0.0,1
10,347785260789835,0.0,0.0,1.0,1,0.0,0.0,1.0,1
11,365882020742330,1.0,0.0,0.0,1,1.0,0.0,0.0,1
12,416301579449694,0.0,0.0,1.0,1,0.0,0.0,1.0,1
13,420449720220692,0.0,0.0,1.0,1,0.0,0.0,1.0,1
14,448610188195811,0.0,0.0,2.0,2,0.0,0.0,2.0,2
15,456015810461357,0.0,0.0,1.0,1,0.0,0.0,1.0,1
16,457867161681660,0.0,1.0,0.0,1,0.0,1.0,0.0,1
17,468235013311868,0.0,1.0,0.0,1,0.0,1.0,0.0,1
18,475635010681369,0.0,2.0,0.0,2,0.0,2.0,0.0,2
19,519199987760489,1.0,0.0,0.0,1,1.0,0.0,0.0,1
20,530786270564316,1.0,0.0,0.0,1,1.0,0.0,0.0,1
21,538200907470757,0.0,1.0,0.0,1,0.0,1.0,0.0,1
22,558877640599287,1.0,0.0,0.0,1,1.0,0.0,0.0,1
23,622102439689666,0.0,2.0,1.0,3,0.0,2.0,1.0,3
24,642751118419841,0.0,1.0,0.0,1,0.0,1.0,0.0,1
25,655267966876774,1.0,0.0,0.0,1,1.0,0.0,0.0,1
26,717556230663455,0.0,0.0,1.0,1,0.0,0.0,1.0,1
27,719819620272773,0.0,0.0,1.0,1,0.0,0.0,1.0,1
28,732881181016646,0.0,1.0,0.0,1,0.0,1.0,0.0,1
29,759186287310366,0.0,0.0,1.0,1,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...
393535,9222439452676054246,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393536,9222445878176178987,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393537,9222505600439168461,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393538,9222517399250029400,1.0,0.0,0.0,1,1.0,0.0,0.0,1
393539,9222605308741024421,2.0,0.0,0.0,2,2.0,0.0,0.0,2
393540,9222608508750105493,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393541,9222775201174486974,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393542,9222809061253378785,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393543,9222820903899321555,0.0,2.0,0.0,2,0.0,2.0,0.0,2
393544,9222828776091827087,0.0,0.0,3.0,3,0.0,0.0,3.0,3
393545,9222848912066710170,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393546,9222856470568969120,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393547,9222861184027496933,1.0,0.0,0.0,1,1.0,0.0,0.0,1
393548,9222891164638072546,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393549,9222941581432951568,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393550,9222957264925735246,4.0,0.0,0.0,4,4.0,0.0,0.0,4
393551,9223065111245755115,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393552,9223066346652706056,1.0,0.0,0.0,1,1.0,0.0,0.0,1
393553,9223135580643723279,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393554,9223180934071401185,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393555,9223189551280812934,2.0,0.0,0.0,2,2.0,0.0,0.0,2
393556,9223229584859890420,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393557,9223231006535555583,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393558,9223250784891904112,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393559,9223252295312976945,1.0,0.0,1.0,2,1.0,0.0,1.0,2
393560,9223291601074715510,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393561,9223314893254762361,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393562,9223332684447638624,0.0,1.0,0.0,1,0.0,1.0,0.0,1
393563,9223336706138545892,0.0,0.0,1.0,1,0.0,0.0,1.0,1
393564,9223365873867066370,0.0,0.0,1.0,1,0.0,0.0,1.0,1